{% extends bento_base_template %}
{% block SETUP_BENTO_COMPONENTS %}
ENV CUDA_HOME /usr/local/cuda
LABEL org.opencontainers.image.source="https://github.com/Saksham0207/b_t.git"
{{ super() }}
RUN pip install torch==2.0.1+cu118 torchvision==0.15.2+cu118 torchaudio==2.0.2 --index-url https://download.pytorch.org/whl/cu118
{% endblock %}
